### ISSUE TITLE
Crossings show a glitch

### ISSUE THREAD

**Issue by Sipke82** [bloodypenguin/Skylines-MetroOverhaulMod#19]
Crossings show a glitch:
https://i.snag.gy/NemAFb.jpg

**Comment by andreharv** [comment]
I don't see it.  If you are talking about the squiggly dark things, they are meant to be there.  You see them a lot on level crossings with third rails.  Keeps peep from frying themselves.

**Comment by Sipke82** [comment]
Ah ok, didn't know. Thanks
