### ISSUE TITLE
not compatible with More Vehicles

### ISSUE THREAD

**Issue by benklop** [bloodypenguin/Skylines-MetroOverhaulMod#22]
I can confirm that the simulation is frozen when trying to use MOM and More Vehicles simultaneously. (also reported to More Vehicles here: https://github.com/dymanoid/MoreVehicles/issues/2)

**Comment by bloodypenguin** [comment]
Should be fixed with this:
https://github.com/bloodypenguin/Skylines-MetroOverhaulMod/commit/9e7a34cf3c22072d78eadce5294c518b27a01649
awaiting the release
