### ISSUE TITLE
Dll and other files

### ISSUE THREAD

**Issue by EC-O-DE** [bloodypenguin/Skylines-MetroOverhaulMod#3]
When the mod is downloaded to my steam folder, there a bunch of other files too. Is the DLL only what elevated station users need,and the rest is for asset creators?

**Comment by boformer** [comment]
no. The other files are models for the elevated track, which are loaded by the mod. Just don't touch them.

**Comment by EC-O-DE** [comment]
Ok so all files needed, thanks for the reply. No wonder my perfectly previous working city save did not work.. It's clear now. Thanks.
