### ISSUE TITLE
Station track with platform between tracks

### ISSUE THREAD

**Issue by boformer** [bloodypenguin/Skylines-MetroOverhaulMod#4]
The station tracks are kind of isolated from other train tracks. There is only one "connection piece".

It should be easy to create tracks like this, where the platform is between the 2 tracks:

```
4m track | 4m platform | 4m platform | 4m track
or
4m track | 4m platform | 4m gap | 4m platform | 4m track
```

![image](http://www.bahnbilder.de/bilder/in-mitte-bahnsteige-fuehrt-ein-175349.jpg)

**Comment by eiclu** [comment]
Is there any update on this? I would really like to use this

**Comment by boformer** [comment]
This would be quite difficult, but it is not impossible.
